name: PlutoExampleBuilder

on:
  workflow_dispatch:
  push:
    branches: 
      - pluto-test
    paths:
      - 'src/**'
      - 'examples/src/**'
      - '.github/workflows/PlutoExampleBuilder.yml'
      - 'Project.toml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v3

      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
            version: '1.10'

      - run: julia -e 'using Pkg; Pkg.add("PlutoSliderServer"); Pkg.add("FMIFlux")'
      - run: julia -e 'using PlutoSliderServer; PlutoSliderServer.export_directory("examples/src/pluto")'

      - name: Archive examples artifacts (success)
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: pluto-dbg
          path: examples/src/*
          
      - name: Archive examples artifacts (failure)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: pluto-dbg
          path: examples/src/*
